version: "3"

services:
  app-cabonorte:
    container_name: app-cabonorte
    #image: app-petitstore
    build: .
    restart: unless-stopped
    ports:
      - "8100:80"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:cabonorte.paraanime.com
      - traefik.port=80
      - traefik.docker.network=web
      #- traefik.docker.network=default
      - traefik.frontend.protocol=http
      - traefik.frontend.entryPoints=http,https
    networks:
      - web
      #- default

networks:
  #default:
    #external: true
  web:
    external: true
